server:
 port: 9090
spring:
  application:
    name: ecomm-backend
  datasource:
     username: suneel
     password: welcome
     url: jdbc:oracle:thin:@localhost:1521:xe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
   rest:
    base-path: /api    
    
    
  
